chore: improve checks

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -17,10 +17,17 @@ jobs:
 
       - name: Check versions
         run: |
-          pVersion=$(cat package.json | jq -r '.version')
-          pLVersion=$(cat package-lock.json | jq -r '.version')
-          if ["$pVersion" != "$plockVersion"]; then
-            echo "::error file=package-lock.json::Must update package-lock.json version too, use 'npm install'."
+          officialVersion=$(cat package.json | jq -r '.version')
+          lockVersion1=$(cat package-lock.json | jq -r '.version')
+          lockVersion2=$(cat package-lock.json | jq -r '.packages | .[] | select(.name == "floor-bot") | .version')
+
+          if ["$officialVersion" != "$lockVersion1"]; then
+            echo "::error file=package-lock.json::Must update package-lock.json main version too, use 'npm install'."
+            exit 1
+          fi
+
+          if ["$officialVersion" != "$lockVersion2"]; then
+            echo "::error file=package-lock.json::Must update package-lock.json dependency version too, use 'npm install'."
             exit 1
           fi
 
