chore: improve CI

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -1,13 +1,29 @@
-# This is a basic workflow to help you get started with Actions
 
-name: checks
+name: lint
 
-# Controls when the workflow will run
 on:
   pull_request:
     branches: [ master ]
 
 jobs:
+  check-version-populate:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Install jq
+        run: sudo apt install jq -y
+
+      - name: Check versions
+        run: |
+          pVersion=$(cat package.json | jq -r '.version')
+          pLVersion=$(cat package-lock.json | jq -r '.version')
+          if ["$pVersion" != "$plockVersion"]; then
+            echo "::error file=package-lock.json::Must update package-lock.json version too, use 'npm install'."
+            exit 1
+          fi
+
   run-version-update:
     runs-on: ubuntu-latest
     steps:
